//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace RImageSchemas.Serialization.Orders.Production {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class ProductionOrderStatus {
        
        /// <remarks/>
        public Status Status;
        
        /// <remarks/>
        public Timestamps Timestamps;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Device")]
        public Device[] Device;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServerId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Originator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginalOrder;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class Status {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusState State;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusStage Stage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusStageEx StageEx;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StageExSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorMessage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActionWithError;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CopiesRequested;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CopiesCompleted;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PercentCompleted;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OutputMailslot;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BarcodeValue;
    }
    
    /// <remarks/>
    public enum StatusState {
        
        /// <remarks/>
        NOT_STARTED,
        
        /// <remarks/>
        IN_PROCESS,
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        FAILED,
    }
    
    /// <remarks/>
    public enum StatusStage {
        
        /// <remarks/>
        WAITING,
        
        /// <remarks/>
        BUSY,
        
        /// <remarks/>
        DOWNLOADING,
        
        /// <remarks/>
        RECORDING,
        
        /// <remarks/>
        FIXATING,
        
        /// <remarks/>
        DESTROYING,
        
        /// <remarks/>
        PRINTING,
        
        /// <remarks/>
        MAPPING,
        
        /// <remarks/>
        READING,
        
        /// <remarks/>
        COMPLETED,
    }
    
    /// <remarks/>
    public enum StatusStageEx {
        
        /// <remarks/>
        SUSPENDING,
        
        /// <remarks/>
        SUSPENDED,
        
        /// <remarks/>
        CANCELLING,
        
        /// <remarks/>
        SEGMENT,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class Device {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DeviceCurrentState CurrentState;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PercentDone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RejectMessage;
    }
    
    /// <remarks/>
    public enum DeviceCurrentState {
        
        /// <remarks/>
        WAITING,
        
        /// <remarks/>
        DOWNLOADING,
        
        /// <remarks/>
        LOADING,
        
        /// <remarks/>
        CHECKING_DISC,
        
        /// <remarks/>
        RECORDING,
        
        /// <remarks/>
        FIXATING,
        
        /// <remarks/>
        VERIFYING,
        
        /// <remarks/>
        QUEUED_FOR_FIFO,
        
        /// <remarks/>
        UNLOADING,
        
        /// <remarks/>
        REJECTING,
        
        /// <remarks/>
        DESTROYING,
        
        /// <remarks/>
        WAITING_FOR_LABEL_RENDERING,
        
        /// <remarks/>
        PRINTING,
        
        /// <remarks/>
        MAPPING,
        
        /// <remarks/>
        READING,
        
        /// <remarks/>
        SUSPENDED,
        
        /// <remarks/>
        WAITING_FOR_NEXT_SEGMENT,
        
        /// <remarks/>
        BUSY,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class Timestamps {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderRead;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderCompleted;
    }
}
